### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#125]
We need a settings page to set the path of the configuration and other configuration options, that would normally be set over the cli. But windows sucks ass so i guess we have to make a settings page for pleps

**Comment by arrowtip** [comment]
switch between control and view panel
demonstration mode
dark mode
comic sans mode

**Comment by kistenklaus** [comment]
maybe later

**Comment by kistenklaus** [comment]
update raspberry pi firmware

**Comment by arrowtip** [comment]
add settings to disable or ignore frontend and deadlock watchdogs in e69cfead361b3fa149f7c689bfa433c5ff8ab621
