### ISSUE TITLE
Graphs are broken

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/canzero#127]
Currently the graphs on the nodepages are broken.
It should not be my fault, atleast I hope so.

**Comment by NiklasHeneka** [comment]
Happended with [1fd32b3](https://github.com/mu-zero-HYPERLOOP/canzero/commit/1fd32b3c8d058712f6851240bea1a925e871f9c2) so it was me. 
But WHY?

**Comment by kistenklaus** [comment]
fixed
