### ISSUE TITLE
unsolicited get responses

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#139]
What would you guys think if we allow nodes to send get responses without them beeing requested. In theory it should work as normal, we could for example allocate a node id let's say 0xFF to be a broadcast of a value. 

So here's the usecase

Let's say we tell the input_board to calibrate the accelerometer when it's done it just sends a get_resp for the estimated variance on each axis and the offset used! There it effectivly no overhead here and it would just be useful to have this data in log files!

**Comment by arrowtip** [comment]
Control panel can take unsolicited get responses
