### ISSUE TITLE
The order of frames in the ObjectEntryObject is incorrect.

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#157]
The order of the frames is not correct in the ObjectEntryObject. They should be sorted by the timestamp not 
the arrival at the ObjectEntryObject. 

Not completely sure, but this might actually brake the graphs =^(. Because they kind of depend on the values beein in the correct order =^(.

**Comment by arrowtip** [comment]
sort during export instead!
