### ISSUE TITLE
recover from heartbeat miss!

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#183]
I would like the heartbeat object entries to recover properly, meaning that if a heartbeat arrives after a miss another function get's called that allows for resetting of the error flag!

**Comment by kistenklaus** [comment]
REALLY HIGH PRIORITY!

**Comment by arrowtip** [comment]
pdu only cuts sdc on heartbeat miss. mother board does all the decisions

**Comment by arrowtip** [comment]
broken invariant in idle should restart  pod
