### ISSUE TITLE
Implement Heartbeat in control-panel

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#91]

**Comment by kistenklaus** [comment]
This should also check for the state of the frontend. 
Here we have two options:
- Have the heartbeat protocol completely in the backend and interlock it with another heartbeat from the frontend.
- Send heartbeats directly from the frontend.

This HAASS to be tested!

**Comment by NiklasHeneka** [comment]
![Image](https://github.com/mu-zero-HYPERLOOP/control-panel/assets/93838730/b492d629-b3c2-42ca-a2c3-a6df955b858a)

**Comment by kistenklaus** [comment]
HEARTBEAT OVERLORD

**Comment by arrowtip** [comment]
if heartbeat from frontend times out send heartbeat message with zero ticks to server.
show frontend modal with timeout if heartbeat from remaining network is missed.

**Comment by arrowtip** [comment]
both in control panel and the nodes, the heartbeats on each bus are completely independent from each other.
registration and deregistration has to be done for each bus separately

**Comment by arrowtip** [comment]
nevermind. heartbeats unregister is independent per bus, but register happens for all buses on first heartbeat on one
