### ISSUE TITLE
Fix Trace page not displaying deprecated frames correctly!

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#92]

**Comment by kistenklaus** [comment]
Frames not received for a longer time 5000ms should be indicated with a greyed out text . I thought this should work, but there is something wrong happening here

**Comment by NiklasHeneka** [comment]
Skipping through the code, the only time I see an opacity depending on the time since the last frame is in ErrorRow.tsx.
Don't know if that should be but does not make much sense at first glance. Also it is 2500ms.

**Comment by NiklasHeneka** [comment]
@kistenklaus pls test now.
