### ISSUE TITLE
implement logging in control-panel

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#97]
open save dialog from object entry page in frontend and save history to csv file

**Comment by kistenklaus** [comment]
kind of works, but not nice enough yet.

Best would probably be to be able to select a range and the object entries that should be exported!

**Comment by kistenklaus** [comment]
Additionally exporting of individual object entries should also be supported

**Comment by NiklasHeneka** [comment]
![Image](https://github.com/mu-zero-HYPERLOOP/control-panel/assets/93838730/72b0c08c-5eec-4fda-b87f-0d2f8fc53851)

**Comment by arrowtip** [comment]
On logging export site: by default all object entries selected.
Each object entry with node name and object entry name.
Add time range as optional arguments (but dont use them yet)

**Comment by NiklasHeneka** [comment]
![Image](https://github.com/mu-zero-HYPERLOOP/control-panel/assets/93838730/5e584d9b-f728-4905-9e31-3a79a652eb65)
